# Generated by Django 4.1.7 on 2023-08-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestion.team"
            ),
        ),
    ]
