# Generated by Django 4.2.4 on 2023-08-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_player_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='status_trading',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('proposed', 'Proposed')], default='pending', max_length=10),
        ),
    ]
