# Generated by Django 4.2.4 on 2023-08-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_messagerie'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerie',
            name='is_original',
            field=models.BooleanField(default=False),
        ),
    ]
