# Generated by Django 4.2.4 on 2023-08-13 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_messagerie_is_original'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagerie',
            old_name='buyer',
            new_name='recever',
        ),
        migrations.AddField(
            model_name='messagerie',
            name='trading_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.trading'),
            preserve_default=False,
        ),
    ]
