# Generated by Django 4.2.4 on 2023-08-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_rename_buyer_messagerie_recever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerie',
            name='status',
            field=models.CharField(choices=[('lus', 'Lus'), ('non lus', 'Non lus'), ('repondu', 'Repondu')], default='pending', max_length=10),
        ),
    ]
