# Generated by Django 4.1.7 on 2023-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0007_alter_messagerie_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="price",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trading",
            name="contre_proposition_price",
            field=models.DecimalField(decimal_places=2, default=66, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trading",
            name="sell_price",
            field=models.DecimalField(decimal_places=2, default=77, max_digits=10),
            preserve_default=False,
        ),
    ]
