# Generated by Django 4.2.4 on 2023-08-16 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestion", "0010_alter_trading_contre_proposition_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trading",
            name="talking_to",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="messagerie",
            name="status",
            field=models.CharField(
                choices=[
                    ("lus", "Lus"),
                    ("non lus", "Non lus"),
                    ("repondu", "Repondu"),
                ],
                default="non lus",
                max_length=10,
            ),
        ),
    ]
