# Generated by Django 4.2.4 on 2023-08-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0011_trading_talking_to_alter_messagerie_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trading",
            name="info",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
