# Generated by Django 4.2.4 on 2023-08-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0013_alter_trading_status_trading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="player",
            name="value",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
