# Generated by Django 4.2.4 on 2023-08-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0014_alter_player_price_alter_player_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagerie",
            name="player_trading",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.player",
            ),
        ),
    ]
