# Generated by Django 4.2.4 on 2023-08-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0015_messagerie_player_trading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagerie",
            name="player_trading",
        ),
    ]
