# Generated by Django 4.2.4 on 2023-08-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0016_remove_messagerie_player_trading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trading",
            name="status_trading",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("proposed", "Proposed"),
                    ("closed", "closed"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
