# Generated by Django 4.2.4 on 2023-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0018_alter_trading_status_trading"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="budget",
            field=models.DecimalField(
                decimal_places=0, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trading",
            name="contre_proposition_price",
            field=models.DecimalField(
                decimal_places=0, default=None, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trading",
            name="sell_price",
            field=models.DecimalField(
                decimal_places=0, default=None, max_digits=10, null=True
            ),
        ),
    ]
