# Generated by Django 4.2.4 on 2023-08-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0020_profil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trading",
            name="proposed_value",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
