# Generated by Django 4.2.4 on 2023-08-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0021_alter_trading_proposed_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagerie",
            name="trading_number",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.trading",
            ),
        ),
    ]
