# Generated by Django 4.2.4 on 2023-08-26 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_team_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attaque',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='player',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Random', 'Random'), ('Normal', 'Normal'), ('Prometteur', 'Promotteur'), ('Team_Star', 'Team_Star'), ('Internationnal', 'Internationnal'), ('Superstar', 'Superstar'), ('Legend', 'Legend')], default='Random', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='defense',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='player',
            name='feet',
            field=models.CharField(blank=True, choices=[('Right', 'R'), ('Left', 'L'), ('RL', 'RL')], default='R', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='general',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='player',
            name='main_position',
            field=models.CharField(blank=True, choices=[('Buteur', 'BU'), ('Ailier_droit', 'AD'), ('Aillier_gauche', 'AG'), ('Milieu_Offensif', 'MO'), ('Milieu_droit', 'MD'), ('Milieu_Gauche', 'MG'), ('Milieu_Centrale', 'MC'), ('Milieu_defensif', 'MDC'), ('Defenseur_Gauche', 'DG'), ('Defenseur_Droit', 'DD'), ('Defenseur_Centrale', 'DC'), ('Goalkipper', 'GK')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='second_position',
            field=models.CharField(blank=True, choices=[('Buteur', 'BU'), ('Ailier_droit', 'AD'), ('Aillier_gauche', 'AG'), ('Milieu_Offensif', 'MO'), ('Milieu_droit', 'MD'), ('Milieu_Gauche', 'MG'), ('Milieu_Centrale', 'MC'), ('Milieu_defensif', 'MDC'), ('Defenseur_Gauche', 'DG'), ('Defenseur_Droit', 'DD'), ('Defenseur_Centrale', 'DC'), ('Goalkipper', 'GK')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(220)], verbose_name='Taille (cm)'),
        ),
        migrations.AddField(
            model_name='player',
            name='style',
            field=models.CharField(blank=True, choices=[('Artiste', 'Artiste'), ('Dog', 'Dog'), ('Elegant', 'Elegant'), ('Killer', 'Killer'), ('Fidele', 'Fidele'), ('Leader', 'Leader'), ('Runner', 'Runner'), ('Fighter', 'Fighter')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='third_position',
            field=models.CharField(blank=True, choices=[('Buteur', 'BU'), ('Ailier_droit', 'AD'), ('Aillier_gauche', 'AG'), ('Milieu_Offensif', 'MO'), ('Milieu_droit', 'MD'), ('Milieu_Gauche', 'MG'), ('Milieu_Centrale', 'MC'), ('Milieu_defensif', 'MDC'), ('Defenseur_Gauche', 'DG'), ('Defenseur_Droit', 'DD'), ('Defenseur_Centrale', 'DC'), ('Goalkipper', 'GK')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(110)], verbose_name='Poids (kg)'),
        ),
    ]
