# Generated by Django 4.2.4 on 2023-08-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_player_attaque_player_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationnality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='style',
            field=models.CharField(blank=True, choices=[('Random', 'Random'), ('Artiste', 'Artiste'), ('Dog', 'Dog'), ('Elegant', 'Elegant'), ('Killer', 'Killer'), ('Fidele', 'Fidele'), ('Leader', 'Leader'), ('Runner', 'Runner'), ('Fighter', 'Fighter')], max_length=15, null=True),
        ),
    ]
