# Generated by Django 4.2.4 on 2023-08-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0025_player_nationnality_alter_player_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profil",
            name="team_profil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.team",
            ),
        ),
    ]
