# Generated by Django 4.2.4 on 2023-08-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0026_alter_profil_team_profil"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="second_name",
            field=models.CharField(
                blank=True, default="John", max_length=100, null=True
            ),
        ),
    ]
