# Generated by Django 4.2.4 on 2023-09-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0028_player_interception_player_mental_player_passe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
