# Generated by Django 4.2.4 on 2023-09-19 11:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0030_delete_formation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerInTeamFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Buteur", "BU"),
                            ("Ailier_droit", "AD"),
                            ("Aillier_gauche", "AG"),
                            ("Milieu_Offensif", "MO"),
                            ("Milieu_droit", "MD"),
                            ("Milieu_Gauche", "MG"),
                            ("Milieu_Centrale", "MC"),
                            ("Milieu_defensif", "MDC"),
                            ("Defenseur_Gauche", "DG"),
                            ("Defenseur_Droit", "DD"),
                            ("Defenseur_Centrale", "DC"),
                            ("Goalkipper", "GK"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="player",
            name="is_starter",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=99,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
            ),
        ),
        migrations.CreateModel(
            name="TeamFormation_433",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formation_name", models.CharField(max_length=100)),
                (
                    "players",
                    models.ManyToManyField(
                        through="gestion.PlayerInTeamFormation", to="gestion.player"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playerinteamformation",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestion.player"
            ),
        ),
        migrations.AddField(
            model_name="playerinteamformation",
            name="team_formation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.teamformation_433",
            ),
        ),
    ]
