# Generated by Django 4.2.4 on 2023-09-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0031_playerinteamformation_player_is_starter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamformation_433",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion.team",
            ),
        ),
    ]
