# Generated by Django 4.2.4 on 2023-09-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0032_teamformation_433_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="position_on_the_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Buteur", "BU"),
                    ("Ailier_droit", "AD"),
                    ("Aillier_gauche", "AG"),
                    ("Milieu_Offensif", "MO"),
                    ("Milieu_Centrale", "MC"),
                    ("Milieu_defensif", "MDC"),
                    ("Defenseur_Gauche", "DG"),
                    ("Defenseur_Droit", "DD"),
                    ("Defenseur_Centrale", "DC"),
                    ("Goalkipper", "GK"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
