# Generated by Django 4.2.4 on 2023-09-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0033_player_position_on_the_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamformation_433",
            name="players",
        ),
        migrations.RemoveField(
            model_name="teamformation_433",
            name="team",
        ),
        migrations.AlterField(
            model_name="player",
            name="position_on_the_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Remplacent", "Rp"),
                    ("Buteur", "BU"),
                    ("Ailier_droit", "AD"),
                    ("Aillier_gauche", "AG"),
                    ("Milieu_Offensif", "MO"),
                    ("Milieu_Centrale", "MC"),
                    ("Milieu_defensif", "MDC"),
                    ("Defenseur_Gauche", "DG"),
                    ("Defenseur_Droit", "DD"),
                    ("Defenseur_Centrale", "DC"),
                    ("Goalkipper", "GK"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="PlayerInTeamFormation",
        ),
        migrations.DeleteModel(
            name="TeamFormation_433",
        ),
    ]
