# Generated by Django 4.2.4 on 2023-09-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0038_alter_formation_player10_poste_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position_on_the_field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Remplacent", "Rp"),
                    ("Buteur", "BU"),
                    ("Ailier_droit", "AD"),
                    ("Ailier_gauche", "AG"),
                    ("Milieu_gauche", "MG"),
                    ("Milieu_droit", "MD"),
                    ("Milieu_defensif", "MDC"),
                    ("Defenseur_Gauche", "DG"),
                    ("Defenseur_Droit", "DD"),
                    ("Defenseur_Cent_G", "DCG"),
                    ("Defenseur_Cent_D", "DCG"),
                    ("Goalkipper", "GK"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
