# Generated by Django 4.2.4 on 2023-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0041_alter_formation_player10_poste_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="injured",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="suspended",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
