# Generated by Django 4.2.4 on 2023-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0046_alter_player_attaque_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="last_trained",
            field=models.DateTimeField(default=0),
        ),
    ]
