# Generated by Django 4.2.4 on 2023-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0047_alter_player_last_trained"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="last_trained",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
